import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import { cloudflareWorkersDevEnvironmentShim } from "alchemy/cloudflare";
import { defineConfig, PluginOption } from "vite";
import tsConfigPaths from "vite-tsconfig-paths";

export default defineConfig({
	server: {
		port: 3000,
	},
	build: {
		target: "esnext",
		rollupOptions: {
			external: ["node:async_hooks", "cloudflare:workers"],
		},
	},
	plugins: [
		tailwindcss() as PluginOption,
		cloudflareWorkersDevEnvironmentShim(),
		tsConfigPaths({
			projects: ["./tsconfig.json"],
		}),
		tanstackStart({
			target: "cloudflare-module",
			tsr: {
				routeTreeFileHeader: [
					"/** biome-ignore-all lint/suspicious/noExplicitAny: code generated by @tanstack/react-start */",
				],
				quoteStyle: "double",
			},
		}),
	],
});
