// import tailwindcss from "@tailwindcss/vite";
import { tanstackStart } from "@tanstack/react-start/plugin/vite";
import viteReact from "@vitejs/plugin-react";
import { cloudflareWorkersDevEnvironmentShim } from "alchemy/cloudflare";
import { defineConfig } from "vite";
import tsConfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  build: {
    target: "esnext",
    rollupOptions: {
      external: ["node:async_hooks", "cloudflare:workers"],
    },
  },
  plugins: [
    // tailwindcss() as PluginOption,
    cloudflareWorkersDevEnvironmentShim(),
    tsConfigPaths({
      projects: ["./tsconfig.json"],
    }),
    tanstackStart({
      customViteReactPlugin: true,
      target: "cloudflare-module",
      tsr: {
        routeTreeFileHeader: [
          "/** biome-ignore-all lint/suspicious/noExplicitAny: code generated by @tanstack/react-start */",
        ],
        quoteStyle: "double",
      },
    }),
    viteReact(),
  ],
});
